### ISSUE TITLE
NullPointerException on Xiaomi

### ISSUE THREAD

**Issue by TarasOryshhij** [valentinilk/compose-shimmer#24]
`Fatal Exception: java.lang.NullPointerException:
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$readObserver$1.invoke(SnapshotStateObserver.kt:164)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$readObserver$1.invoke(SnapshotStateObserver.kt:161)
       at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1900)
       at androidx.compose.runtime.SnapshotMutableStateImpl.getValue(SnapshotState.kt:135)
       at androidx.compose.animation.core.AnimationState.getValue(AnimationState.kt:344)
       at androidx.compose.animation.core.Animatable.getValue(Animatable.kt:79)
       at com.valentinilk.shimmer.ShimmerEffect.draw(ShimmerEffect.kt:72)
       at com.valentinilk.shimmer.ShimmerModifier.draw(ShimmerModifier.kt:45)`

<img width="1145" alt="Снимок экрана 2023-11-30 в 10 23 53" src="https://github.com/valentinilk/compose-shimmer/assets/17122827/495e0b9c-2daf-4beb-ac5f-d9d401100f10">

Version:
api "com.valentinilk.shimmer:compose-shimmer:1.2.0"

**Comment by valentinilk** [comment]
Unfortunately this seems to be a bug within compose: https://issuetracker.google.com/issues/298159434

Let me know if the issues still persists with shimmer `1.3.0`. If it does, I'll wrap it with a try & catch.
